### ISSUE TITLE
metadata in config file

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#321]
Right now sequana pipelines have config files. Those config files must have the following fields:

```
  input_directory: "%(input_directory)s"
  input_extension: "%(input_extension)s"
  input_pattern: "%(input_pattern)s"
  input_samples:
      file1: "%(file1)s"
      file2: "%(file2)s"
```

but sometimes it is too strict and SequanaConfig has a mode argument to specify if the mode is "sequana" or "generic". Yet, it must be specified. 

To know automatically the mode we can add a metadata. 

```
    __snakeformat__ = "generic" 
```

will be recognised and used in SequanaConfig class
